In [1]:
from numpy import *
a=arange(1,10)
print(a)

b=a[1:7:2]
print(b)

b=a[::]
print(b)

b=a[-2:2:-1]
print(b)

b=a[-1:2:-2]
print(b)


[1 2 3 4 5 6 7 8 9]
[2 4 6]
[1 2 3 4 5 6 7 8 9]
[8 7 6 5 4]
[9 7 5]


In [12]:
import numpy as np

a=np.arange(3,12,1)

print(a)

b=a.reshape(3,3)

print(b)



[ 3  4  5  6  7  8  9 10 11]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
